apiVersion: v1
kind: ServiceAccount
metadata:
  name: quantumforge-service-account
  namespace: quantumforge-platform

---

apiVersion: v1
kind: Secret
metadata:
  name: quantumforge-sa-secret
  namespace: quantumforge-platform
  annotations:
    kubernetes.io/service-account.name: "quantumforge-service-account"
type: Opaque
data:
  # This token is just a placeholder. Replace with your actual token data or generate as needed.
  token: $(echo -n 'your-token-here' | base64)

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: quantumforge-service-account
  namespace: quantumforge-platform
secrets:
  - name: quantumforge-sa-secret
